// <auto-generated />
using System;
using GRH_SENTECH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GRH_SENTECH.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502115415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GRH_SENTECH.Models.Conge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<int>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("employe_id");

                    b.Property<string>("Motif")
                        .HasColumnType("text")
                        .HasColumnName("motif");

                    b.Property<int>("Statut")
                        .HasColumnType("integer")
                        .HasColumnName("statut");

                    b.Property<int>("TypeConge")
                        .HasColumnType("integer")
                        .HasColumnName("type_conge");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.ToTable("conges");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Contrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<int>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("employe_id");

                    b.Property<bool>("PeriodeEssai")
                        .HasColumnType("boolean")
                        .HasColumnName("periode_essai");

                    b.Property<decimal>("SalaireBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salaire_base");

                    b.Property<int>("TypeContrat")
                        .HasColumnType("integer")
                        .HasColumnName("type_contrat");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.ToTable("contrats");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("budget");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("code");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("departements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 5000000m,
                            Code = "DG",
                            Nom = "Direction Générale"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 2000000m,
                            Code = "RH",
                            Nom = "Ressources Humaines"
                        },
                        new
                        {
                            Id = 3,
                            Budget = 3000000m,
                            Code = "INFO",
                            Nom = "Informatique"
                        });
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_naissance");

                    b.Property<int>("DepartementId")
                        .HasColumnType("integer")
                        .HasColumnName("departement_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Genre")
                        .HasColumnType("integer")
                        .HasColumnName("genre");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matricule");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<int>("PosteId")
                        .HasColumnType("integer")
                        .HasColumnName("poste_id");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.HasIndex("PosteId");

                    b.ToTable("employes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 1,
                            Email = "amadou.diallo@sentech.sn",
                            Genre = 1,
                            Matricule = "EMP001",
                            Nom = "Diallo",
                            PosteId = 1,
                            Prenom = "Amadou"
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateTime(1990, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 2,
                            Email = "fatou.ndiaye@sentech.sn",
                            Genre = 2,
                            Matricule = "EMP002",
                            Nom = "Ndiaye",
                            PosteId = 2,
                            Prenom = "Fatou"
                        },
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 3,
                            Email = "ibrahima.sow@sentech.sn",
                            Genre = 1,
                            Matricule = "EMP003",
                            Nom = "Sow",
                            PosteId = 3,
                            Prenom = "Ibrahima"
                        },
                        new
                        {
                            Id = 4,
                            DateNaissance = new DateTime(1995, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 3,
                            Email = "mariama.ba@sentech.sn",
                            Genre = 2,
                            Matricule = "EMP004",
                            Nom = "Ba",
                            PosteId = 4,
                            Prenom = "Mariama"
                        },
                        new
                        {
                            Id = 5,
                            DateNaissance = new DateTime(1992, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 2,
                            Email = "moussa.fall@sentech.sn",
                            Genre = 1,
                            Matricule = "EMP005",
                            Nom = "Fall",
                            PosteId = 2,
                            Prenom = "Moussa"
                        },
                        new
                        {
                            Id = 6,
                            DateNaissance = new DateTime(1998, 9, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 3,
                            Email = "aissatou.gueye@sentech.sn",
                            Genre = 2,
                            Matricule = "EMP006",
                            Nom = "Gueye",
                            PosteId = 5,
                            Prenom = "Aissatou"
                        },
                        new
                        {
                            Id = 7,
                            DateNaissance = new DateTime(1987, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 1,
                            Email = "cheikh.kane@sentech.sn",
                            Genre = 1,
                            Matricule = "EMP007",
                            Nom = "Kane",
                            PosteId = 1,
                            Prenom = "Cheikh"
                        },
                        new
                        {
                            Id = 8,
                            DateNaissance = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 2,
                            Email = "rokhaya.mbaye@sentech.sn",
                            Genre = 2,
                            Matricule = "EMP008",
                            Nom = "Mbaye",
                            PosteId = 2,
                            Prenom = "Rokhaya"
                        },
                        new
                        {
                            Id = 9,
                            DateNaissance = new DateTime(1991, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 3,
                            Email = "oumar.cisse@sentech.sn",
                            Genre = 1,
                            Matricule = "EMP009",
                            Nom = "Cisse",
                            PosteId = 3,
                            Prenom = "Oumar"
                        },
                        new
                        {
                            Id = 10,
                            DateNaissance = new DateTime(1996, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartementId = 3,
                            Email = "khady.toure@sentech.sn",
                            Genre = 2,
                            Matricule = "EMP010",
                            Nom = "Toure",
                            PosteId = 4,
                            Prenom = "Khady"
                        });
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_evaluation");

                    b.Property<int>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("employe_id");

                    b.Property<decimal>("Note")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("note");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("periode");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.ToTable("evaluations");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intitule");

                    b.Property<int>("NiveauHierarchique")
                        .HasColumnType("integer")
                        .HasColumnName("niveau_hierarchique");

                    b.Property<decimal>("SalaireMax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salaire_max");

                    b.Property<decimal>("SalaireMin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salaire_min");

                    b.HasKey("Id");

                    b.ToTable("postes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Intitule = "Directeur Général",
                            NiveauHierarchique = 5,
                            SalaireMax = 1500000m,
                            SalaireMin = 800000m
                        },
                        new
                        {
                            Id = 2,
                            Intitule = "Responsable RH",
                            NiveauHierarchique = 4,
                            SalaireMax = 700000m,
                            SalaireMin = 400000m
                        },
                        new
                        {
                            Id = 3,
                            Intitule = "Développeur Senior",
                            NiveauHierarchique = 3,
                            SalaireMax = 600000m,
                            SalaireMin = 300000m
                        },
                        new
                        {
                            Id = 4,
                            Intitule = "Développeur Junior",
                            NiveauHierarchique = 2,
                            SalaireMax = 300000m,
                            SalaireMin = 150000m
                        },
                        new
                        {
                            Id = 5,
                            Intitule = "Stagiaire",
                            NiveauHierarchique = 1,
                            SalaireMax = 150000m,
                            SalaireMin = 50000m
                        });
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Conge", b =>
                {
                    b.HasOne("GRH_SENTECH.Models.Employe", "Employe")
                        .WithMany("Conges")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Contrat", b =>
                {
                    b.HasOne("GRH_SENTECH.Models.Employe", "Employe")
                        .WithMany("Contrats")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Employe", b =>
                {
                    b.HasOne("GRH_SENTECH.Models.Departement", "Departement")
                        .WithMany("Employes")
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GRH_SENTECH.Models.Poste", "Poste")
                        .WithMany("Employes")
                        .HasForeignKey("PosteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Evaluation", b =>
                {
                    b.HasOne("GRH_SENTECH.Models.Employe", "Employe")
                        .WithMany("Evaluations")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Departement", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Employe", b =>
                {
                    b.Navigation("Conges");

                    b.Navigation("Contrats");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("GRH_SENTECH.Models.Poste", b =>
                {
                    b.Navigation("Employes");
                });
#pragma warning restore 612, 618
        }
    }
}
